name : CI/CD with terraform
on:
    push:
        branches:
            - Complete-CI/CD-with-Terraform-AWS

env:
    AWS_ACCESS_KEY_ID: ${{secrets.}}
    SECRET_ACCESS_KEY: ${{secrets.}}
    AWS_TF_STATE_BUCKET_NAME: ${{secrets.}}
    AWS_SSH_PRIVATE_KEY: ${{secrets.}}
    PUBLIC_KEY: ${{secrets.}}
    AWS_REGION: us-east-1

jobs:
    deploy-infra:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
            uses: actions/checkout@v3
        - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_wrapper: false
        - name: Terraform Init
            id Init
            run: terraform init -backend-config="bucket=$AWS_TF_STATE_BUCKET_NAME" -backend-config="region=$AWS_REGION" -backend-config="key=terraform.tfstate"
            working-directory: ./terraform
        - name: Terraform plan
            id: plan
            run: terraform plan \
                -var="public_key"=$PUBLIC_KEY" \
                -var="private_key=$AWS_SSH_PRIVATE_KEY" \
                -var="region= us-east-1 \
                -var="key_name=deployer_key" \
                -out=PLAN
            working-directory: ./terraform
        - name: Terraform Apply
            id: apply
            run: terraform apply -auto-approve PLAN
            working-directory: ./terraform  
            